[options]

admin_passwd = 123


addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; database
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; tránh warning Odoo 19+
http_interface = 0.0.0.0

